name: Watch Master Data

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual run

jobs:
  check-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download and Update Master Data
        run: |
          mkdir -p data/master
          
          # Download files from sekaimaster
          curl -sS --fail --retry 5 --retry-delay 5 --http1.1 "https://sekaimaster.exmeaning.com/master/events.json" -o data/master/events.json
          curl -sS --fail --retry 5 --retry-delay 5 --http1.1 "https://sekaimaster.exmeaning.com/master/eventCards.json" -o data/master/eventCards.json
          curl -sS --fail --retry 5 --retry-delay 5 --http1.1 "https://sekaimaster.exmeaning.com/master/eventMusics.json" -o data/master/eventMusics.json
          
          # Download files from haruki-sekai-master (GitHub Raw)
          curl -sS --fail --retry 5 --retry-delay 5 --http1.1 "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-master/main/master/virtualLives.json" -o data/master/virtualLives.json
          curl -sS --fail --retry 5 --retry-delay 5 --http1.1 "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-master/main/master/gachas.json" -o data/master/gachas.json
          
          # Check for changes
          if [[ -n $(git status --porcelain data/master) ]]; then
            echo "Changes detected in master data."
            
            git config --global user.name 'Snowy Bot'
            git config --global user.email 'bot@snowy.viewer'
            git add data/master/*.json
            git commit -m "chore: update master data json files"
            git push
          else
            echo "No changes in master data."
          fi
